export const COMMON_COLORS = [
  { name: 'Negro', hex: '#000000' },
  { name: 'Blanco', hex: '#FFFFFF' },
  { name: 'Rojo', hex: '#EF4444' },
  { name: 'Azul', hex: '#2563eb' },
  { name: 'Verde', hex: '#10B981' },
  { name: 'Amarillo', hex: '#F5C81B' },
  { name: 'Gris', hex: '#6B7280' },
  { name: 'Naranja', hex: '#F97316' },
  { name: 'Morado', hex: '#8B5CF6' },
  { name: 'Rosa', hex: '#EC4899' },
  { name: 'Beige', hex: '#F5F5DC' },
  { name: 'Café', hex: '#78350F' },
  { name: 'Cian', hex: '#06B6D4' },
  { name: 'Lima', hex: '#84CC16' },
  { name: 'Dorado', hex: '#D4AF37' },
  { name: 'Plateado', hex: '#C0C0C0' },
  { name: 'Azul Marino', hex: '#1E3A8A' },
  { name: 'Turquesa', hex: '#14B8A6' },
  { name: 'Lila', hex: '#D8B4FE' },
  { name: 'Salmón', hex: '#FA8072' },
  { name: 'Menta', hex: '#D1FAE5' },
  { name: 'Coral', hex: '#FF7F50' },
  { name: 'Indigo', hex: '#6366F1' },
  { name: 'Borgonia', hex: '#800020' },
  { name: 'Verde Oliva', hex: '#808000' },
  { name: 'Marrón Caramelo', hex: '#C68E17' },
  { name: 'Gris Carbón', hex: '#36454F' },
  { name: 'Azul Eléctrico', hex: '#7EF9FF' },
  { name: 'Verde Bosque', hex: '#228B22' },
  { name: 'Crema', hex: '#FFFDD0' },
  { name: 'Ocre', hex: '#CC7722' },
  { name: 'Terracota', hex: '#E2725B' },
  { name: 'Esmeralda', hex: '#50C878' },
  { name: 'Granate', hex: '#800000' },
  { name: 'Ladrillo', hex: '#B22222' },
  { name: 'Arena', hex: '#C2B280' },
  { name: 'Lavanda', hex: '#E6E6FA' },
  { name: 'Mamey', hex: '#FF8B5A' },
  { name: 'Púrpura', hex: '#A020F0' },
  { name: 'Violeta', hex: '#EE82EE' },
  { name: 'Fucsia', hex: '#FF00FF' },
  { name: 'Trigo', hex: '#F5DEB3' },
  { name: 'Mostaza', hex: '#FFDB58' },
  { name: 'Kaki', hex: '#F0E68C' },
  { name: 'Azabache', hex: '#343434' },
  { name: 'Hueso', hex: '#F5F5F5' },
  { name: 'Marfil', hex: '#FFFFF0' },
  { name: 'Chocolate', hex: '#D2691E' },
  { name: 'Plomo', hex: '#757575' },
  { name: 'Cobre', hex: '#B87333' }
];
